language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - nightly
install:
  - composer install --prefer-dist --no-interaction
script:
  - vendor/bin/phpcs -p --standard="PSR2" src
  - vendor/bin/phpunit